package com.alphasystem
package arabic
package morphologicalanalysis
package ui
package service

import arabic.fx.ui.util.*
import javafx.application.Platform
import javafx.concurrent.{ Task, Worker, WorkerStateEvent, Service as JService }
import javafx.event.EventHandler
import org.slf4j.{ Logger, LoggerFactory }
import scalafx.concurrent.Service
import scalafx.scene.Node

abstract class ServiceAdapter[IN, OUT](node: Node) {

  protected val logger: Logger = LoggerFactory.getLogger(getClass)

  def serviceInitializer(f: IN => OUT): IN => Service[OUT] = (in: IN) =>
    new Service[OUT](
      new JService[OUT] {
        override def createTask(): Task[OUT] =
          new Task[OUT]() {
            override def call(): OUT = f(in)
          }
      }
    ) {}

  /** Configures the provided service to handle response events by setting up the appropriate callbacks for success and
    * failure scenarios.
    *
    * @param service
    *   the service whose response handling behavior is to be configured
    */
  def handleResponse(service: Service[OUT]): Unit = {
    service.onSucceeded = onSucceeded
    service.onFailed = onFailed
  }

  /** Starts the given service and ensures proper initialization. If the service is already in a `succeeded`` state, it
    * will be restarted. Otherwise, the service will be started.
    *
    * @param service
    *   the service instance to be started or restarted
    */
  def start(service: Service[OUT]): Unit = {
    val scene = node.getScene
    if Option(scene).isDefined then node.waitCursor()
    Platform.runLater { () =>
      if service.state.value == Worker.State.SUCCEEDED then service.restart()
      else service.start()
    }
  }

  /** Handles the successful completion of a worker's execution. This method processes the successful event, typically
    * performing actions such as updating the UI or triggering subsequent operations.
    *
    * @param event
    *   the worker state event representing the successful completion of the worker
    */
  protected def onSucceeded(event: WorkerStateEvent): Unit = {
    node.defaultCursor()
    val result = event.getSource.getValue.asInstanceOf[OUT]
    doOnSucceeded(event.getSource.getValue.asInstanceOf[OUT])
    event.consume()
  }

  /** Handles the successful processing of the result generated by a service or operation. This method performs
    * follow-up actions such as updating the user interface or triggering further processes based on the output.
    *
    * @param result
    *   the output of the successful service execution or operation
    */
  protected def doOnSucceeded(result: OUT): Unit

  /** Updates the user interface to reflect the failure state of a service or operation. This method is typically
    * invoked as part of the failure-handling logic.
    */
  protected def doOnFailed(): Unit = ()

  /** Handles the failure event for a worker, logging the exception and updating the UI accordingly. This method is
    * invoked when the worker's execution results in a failure.
    *
    * @param event
    *   the worker state event containing details of the failure, including the exception that caused the failure
    */
  protected def onFailed(event: WorkerStateEvent): Unit = {
    node.defaultCursor()
    val exception = event.getSource.getException
    logger.error("Service failed with exception", exception)
    doOnFailed()
    event.consume()
  }
}
