version: '3'
services:
  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=morphological_analysis
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
